"""add phone to customer

Revision ID: 741b7d7ad52f
Revises: 5b45f8f35250
Create Date: 2025-09-17 18:40:31.888152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741b7d7ad52f'
down_revision: Union[str, Sequence[str], None] = '5b45f8f35250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
